############################################################################################################
## terminal appearance
############################################################################################################
alias ls='ls -G'
alias lsf='ls -1d'
export CLICOLOR=1
export LSCOLORS=ExFxCxDxBxegedabagacad

############################################################################################################
## terminal commands
############################################################################################################
alias ll='ls -lrth'
alias l='ls -lrth'
alias rmtilda='rm *~'
alias dh='du -h -d 1'
alias dhs='du -s */ | sort -n'

############################################################################################################
## gotos
############################################################################################################
alias down='cd ~/Downloads'
alias doc='cd ~/Documents'

############################################################################################################
## remove many files
############################################################################################################
rmfiles () {
    perl -e 'for(<*>){((stat)[9]<(unlink))}'
}

############################################################################################################
## top
############################################################################################################
alias t='top -o cpu'

############################################################################################################
## Primary Work Space
############################################################################################################
alias condaupdate='conda update conda'
alias condacreate='conda create -n ${condaname} python=3.11 anaconda'
alias condadone='conda remove -n ${condaname} -all'
alias condaactivate='source activate ${condaname}'
#alias act='conda activate ${condaname}'
alias jup='jupyter notebook'
alias env='cd /Users/tgadfort/anaconda3/envs/${codename}'
alias pyinst='pwd ; python setup.py -q clean ; python setup.py -q install'
alias inst='poetry build'


############################################################################################################
## code
############################################################################################################
#alias code='cd ~/Documents/${condaspace}'
alias note='cd ~/Documents/${condaspace}/pandb/note'
alias update='source ~/.zshrc'

############################################################################################################
## Music DB
############################################################################################################
alias moddb='cd /Volumes/Seagate/Discog'
alias sumdb='cd ~/Music/Discog'
alias rawdb='cd /Volumes/Piggy/Discog'
#alias inst='code ; cd pandb ; pwd ; python setup.py -q clean ; python setup.py -q install'

alias permdb='cd /Users/tgadfort/anaconda3/envs/${condaname}/pandb/musicdb'
alias perm='cd /Users/tgadfort/anaconda3/envs/${condaname}/pandb'
alias saveperm='cp /Users/tgadfort/anaconda3/envs/${condaname}/pandb/musicdb/manualEntries.p ~/Dropbox/'


############################################################################################################
## Torrents
############################################################################################################
alias torrents='cd /Volumes/Seagate/Torrents'

############################################################################################################
## Music
############################################################################################################
#alias mid='python ~/Documents/${condaspace}/mp3id/mid.py'
#alias fixdir='python ~/Documents/${condaspace}/mp3id/fixDirs.py'
#alias mgentag='python ~/Documents/${condaspace}/mp3id/gentags.py'
#alias segment='python ~/Documents/${condaspace}/mp3id/segment.py'
alias matched='cd /Volumes/Piggy/Music/Matched'

############################################################################################################
## VM
############################################################################################################
alias vms='ls /System/Volumes/VM | wc -l'

############################################################################################################
## Remote
############################################################################################################
alias remtest='cd ; cd code ; conda activate post ; jupyter notebook --no-browser --port=9998'
alias remote='jupyter notebook --no-browser --port=9999'
alias rem='code ; act ; remote'

############################################################################################################
## Git
############################################################################################################
git config --global user.name "tgadf"
git config --global user.email tgadfort@gmail.com
git config --global core.editor pico
pyclean () {
    find . -type f -name '*.py[co]' -delete -o -type d -name __pycache__ -delete
}

condaprefix () {
    . ${HOME}/anaconda3/bin/activate
    conda activate ${condaname}
}

condasuffix () {
    alias code='cd ${condaspace}'
}

act () {
    condaname="py311"
    condaprefix
    condaspace="${HOME}/Documents/code"
    condasuffix
}

post () {
    export condaname="post"
    condaprefix
    condaspace="${HOME}/code"
    condasuffix
}

#mmeta () {
mmetadir="${condaspace}/musicmeta"
alias mid='poe --root ${mmetadir} mid'
#echo "mid => ${mid}"
#}


# >>> conda initialize >>>
# !! Contents within this block are managed by 'conda init' !!
__conda_setup="$('/Users/tgadfort/anaconda3/bin/conda' 'shell.zsh' 'hook' 2> /dev/null)"
if [ $? -eq 0 ]; then
    eval "$__conda_setup"
else
    if [ -f "/Users/tgadfort/anaconda3/etc/profile.d/conda.sh" ]; then
        . "/Users/tgadfort/anaconda3/etc/profile.d/conda.sh"
    else
        export PATH="/Users/tgadfort/anaconda3/bin:$PATH"
    fi
fi
unset __conda_setup
# <<< conda initialize <<<

############################################################################################################
## Poetry
############################################################################################################
export PATH="/Users/tgadfort/.local/bin:$PATH"

